/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleLiveRouteImport } from './routes/_console.live'
import { Route as ConsoleLoadsRouteImport } from './routes/_console.loads'
import { Route as ConsoleOverviewRouteImport } from './routes/_console.overview'
import { Route as ConsolePrioritiesRouteImport } from './routes/_console.priorities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleLiveRoute = ConsoleLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLoadsRoute = ConsoleLoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOverviewRoute = ConsoleOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePrioritiesRoute = ConsolePrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof ConsoleLiveRoute
  '/loads': typeof ConsoleLoadsRoute
  '/overview': typeof ConsoleOverviewRoute
  '/priorities': typeof ConsolePrioritiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof ConsoleLiveRoute
  '/loads': typeof ConsoleLoadsRoute
  '/overview': typeof ConsoleOverviewRoute
  '/priorities': typeof ConsolePrioritiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/live': typeof ConsoleLiveRoute
  '/_console/loads': typeof ConsoleLoadsRoute
  '/_console/overview': typeof ConsoleOverviewRoute
  '/_console/priorities': typeof ConsolePrioritiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/loads' | '/overview' | '/priorities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/loads' | '/overview' | '/priorities'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/_console/live'
    | '/_console/loads'
    | '/_console/overview'
    | '/_console/priorities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/live': {
      id: '/_console/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof ConsoleLiveRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/loads': {
      id: '/_console/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof ConsoleLoadsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/overview': {
      id: '/_console/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ConsoleOverviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/priorities': {
      id: '/_console/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof ConsolePrioritiesRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleLiveRoute: typeof ConsoleLiveRoute
  ConsoleLoadsRoute: typeof ConsoleLoadsRoute
  ConsoleOverviewRoute: typeof ConsoleOverviewRoute
  ConsolePrioritiesRoute: typeof ConsolePrioritiesRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleLiveRoute: ConsoleLiveRoute,
  ConsoleLoadsRoute: ConsoleLoadsRoute,
  ConsoleOverviewRoute: ConsoleOverviewRoute,
  ConsolePrioritiesRoute: ConsolePrioritiesRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
